name: Build and Send APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Adjust version as needed

      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release

      - name: Zip APK
        run: zip -r app-release.zip ./build/app/outputs/flutter-apk/app-release.apk
        
      - name: Send APK via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: shadrackmballah80@gmail.com
          # Required sender full name (address can be skipped):
          from: mballahshadrack80@gmail.com # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          attachments: ./app-release.zip
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
          
