name: Build and Send APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Adjust version as needed

      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK to Google Drive
        uses: jakejarvis/google-drive-upload@v2
        with:
          file: ./build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GOOGLE_DRIVE_TOKEN }}
