name: Build and Send APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6' # Adjust version as needed

      - name: Install dependencies
        run: flutter pub get
      
      - name: Build APK
        run: flutter build apk --release

      - name: Zip APK
        run: zip -r app-release.zip ./build/app/outputs/flutter-apk/app-release.apk
        
      - name: Send APK via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          secure: true
          subject: New APK Build
          body: Here is the latest APK build.
          from: mballahshadrack80@gmail.com
          to: shadrackmballah80@gmail.com
          attachments: ./app-release.zip
